version: "2"
services:
    web:
        image: php:7-apache
        ports:
            - "8080:80"
        volumes:
            - ./server:/var/www/html/
volumes:
    persistent:
networks:
    default:
        driver: bridge
